name: PHPUnit Coverage
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: xdebug

      - name: Install dependencies
        run: composer install

      - name: Run tests with coverage
        env:
          XDEBUG_MODE: coverage
        run: vendor/bin/phpunit --coverage-html coverage-report
